baseURL: https://thomaswimart.onrender.com/
languageCode: en-us
title: Thomas WIMART
theme: "PaperMod"

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true


params:
  author: Thomas
  defaultTheme: auto
  displayFullLangName: true
  ShowCodeCopyButtons: true
  ShowReadingTime: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowToc: true

  cover:
    ShowReadingTime: true

  assets:

    favicon: "/favicon.ico/"
    favicon16x16:  "/favicon-16x16.png/"
    favicon32x32:  "/favicon-32x32.png/"
    apple_touch_icon:  "/apple-touch-icon.png/"


  profileMode:
      enabled: true
      title: "Welcome!👋 "  # optional default will be site titl
      subtitle: "You will find here my portfolio, as well as my computer notes. 😊💻"
      imageUrl: "/profile-picture.jpg" # optional
      imageTitle: "photo de moi" # optional
      imageWidth: 185 # custom size
      imageHeight: 185 # custom size
      buttons:
        - name: My Portfolio
          url: "/english/portfolio/"
        - name: My Posts
          url: "/posts/"
            

  socialIcons: # optional
        - name: "LinkedIn"
          url: "https://www.linkedin.com/in/thomas-w-588182221/"
        - name: "Github"
          url: "https://github.com/twimart"



languages:
    en:
        languageName: ":uk:"
        languageAltTitle: Anglais
        weight: 1
        taxonomies:
          category: categories
          tag: tags
          series: series
        menu:
            main:
                - identifier: archives
                  name: Archives
                  url: /archives/
                  weight: 5
                - identifier: search
                  name: Search
                  url: /search/
                  weight: 10

    fr:
        languageName: ":fr:"
        languageAltTitle: French
        weight: 2
        title: "Thomas WIMART"
        taxonomies:
          category: FRcategories
          tag: FRtags
          series: FRseries
        profileMode:
            enabled: true
            title: "Bienvenue! 👋"
            subtitle: "Vous trouverez ici mon portfolio, ainsi que mes notes informatiques. 😊💻"
            imageUrl: "/profile-picture.jpg" # optional
            imageTitle: "une image test" # optional
            imageWidth: 185 # custom size 
            imageHeight: 185 # custom size
            buttons:
              - name: Mon Portfolio
                url: "/fr/french/porfolio/"
              - name: Mes Notes
                url: "/fr/notes/"

        menu:
            main:
                - identifier: archives
                  name: Archives
                  url: /archives/
                  weight: 5
                - identifier: search
                  name: Search
                  url: /search/
                  weight: 10
