baseURL: https://www.thomaswimart.fr/
languageCode: en
title: WIMART Thomas
theme: "PaperMod"

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary


params:
  author: Thomas
  defaultTheme: auto
  displayFullLangName: true
  ShowCodeCopyButtons: true
  ShowReadingTime: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowToc: true
  

  cover:
    ShowReadingTime: true

  assets:
    favicon: "/favicon.ico/"
    favicon16x16:  "/favicon-16x16.png/"
    favicon32x32:  "/favicon-32x32.png/"
    apple_touch_icon:  "/apple-touch-icon.png/"

  label:
    text: "WIMART Thomas"
    icon: /apple-touch-icon.png
    iconHeight: 30
    

  profileMode:
      enabled: true
      title: "Welcome!👋 "  # optional default will be site titl
      subtitle: "You will find here my portfolio, as well as my IT. 😊💻"
      imageUrl: "/profile-picture.jpg" # optional
      imageTitle: "photo de moi" # optional
      imageWidth: 185 # custom size
      imageHeight: 185 # custom size
      buttons:
        - name: My Portfolio
          url: "/english/portfolio/"
        - name: My IT Posts
          url: "/posts/"
        - name: My knowledge network (in French)
          url: "https://thomasgarden.netlify.app/"
            

  socialIcons: # optional
        - name: "LinkedIn"
          url: "https://www.linkedin.com/in/thomas-wimart"
        - name: "Github"
          url: "https://github.com/twimart"
        - name: "Instagram"
          url: "https://www.instagram.com/thomaswimart/"
        - name: "paypal"
          url: "https://paypal.me/thomaswimart"


          

languages:
    en:
        languageName: "🌍 EN "
        languageAltTitle: Anglais
        weight: 1
        taxonomies:
          category: categories
          tag: tags
          series: series
        menu:
            main:
                - identifier: archives
                  name: Archives
                  url: /archives/
                  weight: 5
                - identifier: tags
                  name: Tags
                  url: /tags/
                  weight: 10
                - identifier: search
                  name: Search 🔍
                  url: /search/
                  weight: 15

    fr:
        languageName: "🌍 FR "
        languageAltTitle: French
        weight: 2
        title: "Thomas WIMART"
        taxonomies:
          category: FRcategories
          tag: FRtags
          series: FRseries
        profileMode:
            enabled: true
            title: "Bienvenue! 👋"
            subtitle: "Vous trouverez ici mon portfolio, ainsi que mes notes informatiques. 😊💻"
            imageUrl: "/profile-picture.jpg" # optional
            imageTitle: "une image test" # optional
            imageWidth: 185 # custom size 
            imageHeight: 185 # custom size
            buttons:
              - name: Mon Portfolio
                url: "/fr/french/porfolio/"
              - name: Mes Notes
                url: "/fr/notes/"
              - name: Mon réseau de connaisances 
                url: "https://thomasgarden.netlify.app/"

        menu:
            main:
                - identifier: archives
                  name: Archives
                  url: /archives/
                  weight: 5
                - identifier: tags
                  name: Tags
                  url: /FRtags/
                  weight: 10
                - identifier: search
                  name: Recherche 🔍
                  url: /search/
                  weight: 15
