baseURL: http://example.org/
languageCode: en-us
title: twimart
theme: "PaperMod"


profileMode:
    enabled: true # needs to be explicitly set
    title: ExampleSite
    subtitle: "This is subtitle"
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags
